name: "Balto - Rubocop"
description: "Run rubocop on your repo"
runs:
  using: node12
  main: main.js
branding:
  icon: life-buoy
  color: orange
inputs:
  conclusionLevel:
    description: "Which check run conclusion type to use when annotations are created"
    required: false
    default: "neutral"
