name: Balto

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Locally
        uses: actions/checkout@v2
        with:
          path: "balto-rubocop"
      - name: Read ruby version
        run: echo ::set-output name=RUBY_VERSION::$(cat balto-rubocop/test/.ruby-version | cut -f 1,2 -d .)
        id: rv
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "${{ steps.rv.outputs.RUBY_VERSION }}"
      - uses: ./
        with:
          rootDirectory: balto-rubocop/test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
